set_property IOSTANDARD LVCMOS18 [get_ports cs]
set_property PACKAGE_PIN A14 [get_ports cs]

set_property IOSTANDARD LVCMOS18 [get_ports cs_mon]
set_property IOSTANDARD LVCMOS18 [get_ports Din_mon]
set_property IOSTANDARD LVCMOS18 [get_ports sclk_mon]
set_property PACKAGE_PIN L2 [get_ports sclk_mon]
set_property PACKAGE_PIN G2 [get_ports cs_mon]
set_property PACKAGE_PIN J2 [get_ports Din_mon]

set_property IOSTANDARD LVCMOS18 [get_ports miso]
set_property PACKAGE_PIN B15 [get_ports miso]

set_property IOSTANDARD LVCMOS18 [get_ports o_DV]
set_property PACKAGE_PIN U16 [get_ports o_DV]

set_property IOSTANDARD LVCMOS18 [get_ports spi_sclk]
set_property PACKAGE_PIN B16 [get_ports spi_sclk]

set_property IOSTANDARD LVCMOS18 [get_ports {AN[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {AN[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {AN[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {AN[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CA[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CA[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CA[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CA[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CA[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CA[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CA[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CA[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports clk]

set_property IOSTANDARD LVCMOS18 [get_ports o_RX_DV]
set_property PACKAGE_PIN W5 [get_ports clk]
set_property PACKAGE_PIN E19 [get_ports o_RX_DV]
set_property PACKAGE_PIN W4 [get_ports {AN[3]}]
set_property PACKAGE_PIN V4 [get_ports {AN[2]}]
set_property PACKAGE_PIN U4 [get_ports {AN[1]}]
set_property PACKAGE_PIN U2 [get_ports {AN[0]}]
set_property PACKAGE_PIN V7 [get_ports {CA[7]}]
set_property PACKAGE_PIN U7 [get_ports {CA[6]}]
set_property PACKAGE_PIN V5 [get_ports {CA[5]}]
set_property PACKAGE_PIN U5 [get_ports {CA[4]}]
set_property PACKAGE_PIN V8 [get_ports {CA[3]}]
set_property PACKAGE_PIN U8 [get_ports {CA[2]}]
set_property PACKAGE_PIN W6 [get_ports {CA[1]}]
set_property PACKAGE_PIN W7 [get_ports {CA[0]}]
